version: '2.0'
services:
  web:
    build: .
    ports:
    - "3001:3001"
    links:
    - redis
    environment:
      "REDIS_URL": "redis://redis:6379"
      "NODE_ENV": "production"
  redis:
    image: redis